package mobile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"masterdnsvpn-go/internal/config"
)

// generated by Zanoza's ConfigBuilder (kept in sync manually).
const sampleTOML = `
DOMAINS = ["v.example.com"]
DATA_ENCRYPTION_METHOD = 1
ENCRYPTION_KEY = "test-key"

PROTOCOL_TYPE = "SOCKS5"
LISTEN_IP = "127.0.0.1"
LISTEN_PORT = 41080

SOCKS5_AUTH = false
SOCKS5_USER = "zanoza"
SOCKS5_PASS = "zanoza"
HTTP_PROXY_ENABLED = true
HTTP_PROXY_PORT = 41081
SOCKS_OPTIMISTIC_CONNECT = true
LOCAL_HANDSHAKE_TIMEOUT_SECONDS = 30.0

LOCAL_DNS_ENABLED = false
LOCAL_DNS_IP = "127.0.0.1"
LOCAL_DNS_PORT = 53
LOCAL_DNS_CACHE_MAX_RECORDS = 10000
LOCAL_DNS_CACHE_TTL_SECONDS = 14400.0
LOCAL_DNS_PENDING_TIMEOUT_SECONDS = 300.0
DNS_RESPONSE_FRAGMENT_TIMEOUT_SECONDS = 60.0
LOCAL_DNS_CACHE_PERSIST_TO_FILE = false
LOCAL_DNS_CACHE_FLUSH_INTERVAL_SECONDS = 60.0

RESOLVER_BALANCING_STRATEGY = 3
PACKET_DUPLICATION_COUNT = 3
SETUP_PACKET_DUPLICATION_COUNT = 4
STREAM_RESOLVER_FAILOVER_RESEND_THRESHOLD = 2
STREAM_RESOLVER_FAILOVER_COOLDOWN = 2.5
RECHECK_INACTIVE_SERVERS_ENABLED = true
AUTO_DISABLE_TIMEOUT_SERVERS = true
AUTO_DISABLE_TIMEOUT_WINDOW_SECONDS = 30.0
BASE_ENCODE_DATA = false

UPLOAD_COMPRESSION_TYPE = 0
DOWNLOAD_COMPRESSION_TYPE = 0
COMPRESSION_MIN_SIZE = 120

MIN_UPLOAD_MTU = 38
MIN_DOWNLOAD_MTU = 200
MAX_UPLOAD_MTU = 150
MAX_DOWNLOAD_MTU = 4000
AUTO_REMOVE_LOW_MTU_SERVERS = true
MTU_TEST_RETRIES = 2
MTU_TEST_TIMEOUT = 2.0
MTU_TEST_PARALLELISM = 32
SAVE_MTU_SERVERS_TO_FILE = false

RX_TX_WORKERS = 4
TUNNEL_PROCESS_WORKERS = 6
TUNNEL_PACKET_TIMEOUT_SECONDS = 10.0
DISPATCHER_IDLE_POLL_INTERVAL_SECONDS = 0.020
RX_CHANNEL_SIZE = 4096
SOCKS_UDP_ASSOCIATE_READ_TIMEOUT_SECONDS = 30.0
CLIENT_TERMINAL_STREAM_RETENTION_SECONDS = 45.0
CLIENT_CANCELLED_SETUP_RETENTION_SECONDS = 120.0

SESSION_INIT_RETRY_BASE_SECONDS = 1.0
SESSION_INIT_RETRY_STEP_SECONDS = 1.0
SESSION_INIT_RETRY_LINEAR_AFTER = 5
SESSION_INIT_RETRY_MAX_SECONDS = 60.0
SESSION_INIT_BUSY_RETRY_INTERVAL_SECONDS = 60.0
SESSION_INIT_RACING_COUNT = 3

PING_AGGRESSIVE_INTERVAL_SECONDS = 0.100
PING_LAZY_INTERVAL_SECONDS = 0.750
PING_COOLDOWN_INTERVAL_SECONDS = 2.0
PING_COLD_INTERVAL_SECONDS = 15.0
PING_WARM_THRESHOLD_SECONDS = 8.0
PING_COOL_THRESHOLD_SECONDS = 20.0
PING_COLD_THRESHOLD_SECONDS = 30.0

MAX_PACKETS_PER_BATCH = 8
ARQ_WINDOW_SIZE = 1000
ARQ_INITIAL_RTO_SECONDS = 0.5
ARQ_MAX_RTO_SECONDS = 3.0
ARQ_CONTROL_INITIAL_RTO_SECONDS = 0.5
ARQ_CONTROL_MAX_RTO_SECONDS = 2.0
ARQ_MAX_CONTROL_RETRIES = 126
ARQ_INACTIVITY_TIMEOUT_SECONDS = 1800.0
ARQ_DATA_PACKET_TTL_SECONDS = 2400.0
ARQ_CONTROL_PACKET_TTL_SECONDS = 1200.0
ARQ_MAX_DATA_RETRIES = 126
ARQ_DATA_NACK_MAX_GAP = 32
ARQ_DATA_NACK_INITIAL_DELAY_SECONDS = 0.1
ARQ_DATA_NACK_REPEAT_SECONDS = 0.8
ARQ_TERMINAL_DRAIN_TIMEOUT_SECONDS = 120.0
ARQ_TERMINAL_ACK_WAIT_TIMEOUT_SECONDS = 90.0

LOG_LEVEL = "INFO"
`

const sampleResolvers = `
1.1.1.1
8.8.8.8
9.9.9.9
`

// Validates that a TOML payload shaped exactly like the one Zanoza's
// Swift ConfigBuilder emits is accepted by MasterDnsVPN's loader, including
// resolver discovery via the runtime directory.
func TestZanozaGeneratedConfigLoads(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "client_config.toml")
	resPath := filepath.Join(dir, "client_resolvers.txt")
	if err := os.WriteFile(cfgPath, []byte(sampleTOML), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(resPath, []byte(sampleResolvers), 0o600); err != nil {
		t.Fatal(err)
	}

	cfg, err := config.LoadClientConfig(cfgPath)
	if err != nil {
		t.Fatalf("LoadClientConfig: %v", err)
	}
	if cfg.ListenPort != 41080 {
		t.Errorf("ListenPort: got %d want 41080", cfg.ListenPort)
	}
	if cfg.ProtocolType != "SOCKS5" {
		t.Errorf("ProtocolType: got %q want SOCKS5", cfg.ProtocolType)
	}
	if !cfg.HTTPProxyEnabled || cfg.HTTPProxyPort != 41081 || !cfg.SocksOptimisticConnect {
		t.Errorf("compatibility listeners were not loaded: enabled=%v port=%d optimistic=%v", cfg.HTTPProxyEnabled, cfg.HTTPProxyPort, cfg.SocksOptimisticConnect)
	}
	if len(cfg.Domains) != 1 || cfg.Domains[0] != "v.example.com" {
		t.Errorf("Domains: got %v", cfg.Domains)
	}
	if cfg.EncryptionKey != "test-key" {
		t.Errorf("EncryptionKey: got %q", cfg.EncryptionKey)
	}
	if len(cfg.Resolvers) == 0 {
		t.Errorf("Resolvers should be populated from runtimeDir/client_resolvers.txt")
	}
}

func TestStartRejectsBlankRuntimeDir(t *testing.T) {
	err := Start("DOMAINS = [\"x\"]\n", "1.1.1.1\n", "")
	if err == nil {
		t.Fatal("expected error for blank runtime dir")
	}
	if !strings.Contains(err.Error(), "runtimeDir") {
		t.Errorf("error should mention runtimeDir: %v", err)
	}
}

func TestStopWhenNotRunningIsNoop(t *testing.T) {
	Stop()
	if IsRunning() {
		t.Error("IsRunning must report false after Stop on idle client")
	}
}

func TestSetBoundInterfaceRoundtrips(t *testing.T) {
	SetBoundInterface("")
	if got := BoundInterface(); got != "" {
		t.Fatalf("BoundInterface after reset = %q, want empty", got)
	}
	SetBoundInterface("en0")
	if got := BoundInterface(); got != "en0" {
		t.Errorf("BoundInterface = %q, want en0", got)
	}
	SetBoundInterface("")
}

func TestSetBoundAddressRoundtrips(t *testing.T) {
	SetBoundAddress("", "")
	SetBoundAddress("192.0.2.5", "2001:db8::5")
	if got := BoundIPv4(); got != "192.0.2.5" {
		t.Errorf("BoundIPv4 = %q, want 192.0.2.5", got)
	}
	if got := BoundIPv6(); got != "2001:db8::5" {
		t.Errorf("BoundIPv6 = %q, want 2001:db8::5", got)
	}
	SetBoundAddress("", "")
	if got := BoundIPv4(); got != "" {
		t.Errorf("BoundIPv4 after reset = %q", got)
	}
}
